name: netflix-viewer 
version: '0.9.0'
summary: Netflix website as a linux application
description: |
  This is a simple linux app running netflix.com in a browser.
  The motivation is to have a standard NetFlix app that Ubuntu desktop users
  can easily access and add to favorites.

icon: snap/gui/icon.png
architectures:
  - build-on: amd64
    run-on: amd64
license: GPL-3.0

grade: devel 
confinement: strict 
base: core18

compression: lzo


parts:
  netflix-viewer:
    source: .
    plugin: nil


    build-snaps:
    - node/14/stable
  
    build-packages:
    - curl
    - git

    stage-packages:
     - libnss3
     - libnspr4

    override-build: |
      echo "Running override-build script"

      if [ -n "$http_proxy" ]; then
          echo "Add proxies"
          echo "https_proxy: " $https_proxy
          echo "http_proxy: " $http_proxy

          export ELECTRON_GET_USE_PROXY=1
          export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
          export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"

          npm config set proxy $http_proxy
          npm config set https-proxy $https_proxy
      fi

      npm config set prefix ~/.npm
      echo "When building locally use sudo for npm install"
      npm install
      npm run dist
      
      
      cp -r --parents dist/linux-unpacked/* $SNAPCRAFT_PRIME/

apps:
  netflix-viewer:
    extensions: [gnome-3-34]
    desktop: $SNAPCRAFT_PROJECT_DIR/snap/gui/netflix-viewer.desktop
    command:  dist/linux-unpacked/netflix-viewer --no-sandbox 
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - unity7
    - alsa
    - browser-support
    - network
    - opengl
    - audio-playback
